name: major_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.3
  # --- Firebase Core ---
  firebase_core: ^4.2.0

  # --- Firebase Authentication ---
  firebase_auth: ^6.1.1
  google_sign_in: ^6.2.2

  # --- Cloud Firestore (Database) ---
  cloud_firestore: ^6.0.3
  firebase_database: ^12.0.3
  firebase_storage: ^13.0.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  url_launcher: ^6.1.11
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.0.0
  intl: ^0.19.0
  http: ^1.1.0
  uuid: ^4.5.1
  # --- Icons ---
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false # Disabled as ios directory is missing
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FF2D55"
  adaptive_icon_foreground: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/candidate1.png
    - assets/candidate2.png
    - assets/candidate3.png
    - assets/google_logo.png